"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JVar = exports.JLog = exports.JR = exports.JDate = exports.JUnCaughtException = exports.JWarning = exports.JUnhandledRejection = exports.JExit = exports.JColorRandom = void 0;
const faker_1 = require("./faker");
Object.defineProperty(exports, "JColorRandom", { enumerable: true, get: function () { return faker_1.JColorRandom; } });
const faker_2 = require("./faker");
Object.defineProperty(exports, "JExit", { enumerable: true, get: function () { return faker_2.JExit; } });
const faker_3 = require("./faker");
Object.defineProperty(exports, "JUnhandledRejection", { enumerable: true, get: function () { return faker_3.JUnhandledRejection; } });
const faker_4 = require("./faker");
Object.defineProperty(exports, "JWarning", { enumerable: true, get: function () { return faker_4.JWarning; } });
const faker_5 = require("./faker");
Object.defineProperty(exports, "JUnCaughtException", { enumerable: true, get: function () { return faker_5.JUnCaughtException; } });
const faker_6 = require("./faker");
Object.defineProperty(exports, "JDate", { enumerable: true, get: function () { return faker_6.JDate; } });
const faker_7 = require("./faker");
Object.defineProperty(exports, "JR", { enumerable: true, get: function () { return faker_7.JR; } });
const faker_8 = require("./faker");
Object.defineProperty(exports, "JLog", { enumerable: true, get: function () { return faker_8.JLog; } });
const faker_9 = require("./faker");
Object.defineProperty(exports, "JVar", { enumerable: true, get: function () { return faker_9.JVar; } });
