import { JColorRandom } from "./faker";
import { JExit } from "./faker";
import { JUnhandledRejection } from "./faker";
import { JWarning } from "./faker";
import { JUnCaughtException } from "./faker";
import { JDate } from "./faker";
import { JR } from "./faker";
import { JLog } from "./faker";
import { JVar } from "./faker";
export { JColorRandom };
export { JExit };
export { JUnhandledRejection };
export { JWarning };
export { JUnCaughtException };
export { JDate };
export { JR };
export { JLog };
export { JVar };
